# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sash-Plugin-VerticalResponse
version:      1.02
version_from: lib/Sash/Plugin/VerticalResponse.pm
installdirs:  site
requires:
    Sash::Plugin::Base:            1
    VR::API:                       1
    VR::API::Partner:              1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
