# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sash-Plugin-VerticalResponse
version:      1.0
version_from: lib/VerticalResponse.pm
installdirs:  site
requires:
    Sash:                          1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
